language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "7"
  - "6"
  - "5"

script:
  - yarn lint
  - yarn run test
  - yarn build

after_success:
  - yarn run test-cover
